from Services.utils import get

QUEUE_BROKER_URL = get("QUEUE_BROKER_URL")

QUEUE_PACKAGES_NAME = get("QUEUE_PACKAGES_NAME")
QUEUE_DEAD_LETTER_PACKAGES_NAME = get("QUEUE_DEAD_LETTER_PACKAGES_NAME")
QUEUE_DELIVERED_NAME = get("QUEUE_DELIVERED_NAME")
QUEUE_NO_DELIVERED_NAME = get("QUEUE_NO_DELIVERED_NAME")
